server:
  port: 8080

spring:
  application:
    name: cash-loan-service
  data:
    mongodb:
      host: ${SOP_APP_SERVICE_MONGO_HOST:127.0.0.1}
      port: ${SOP_APP_SERVICE_MONGO_PORT:27017}
      username: ${SOP_APP_SERVICE_MONGO_USERNAME:agency}
      password: ${SOP_APP_SERVICE_MONGO_PWD:agency}
      database: ${SOP_APP_SERVICE_MONGO_DATABASE:agency}
---
spring:
  profiles: test
  data:
    mongodb:
      host: ${SOP_APP_SERVICE_MONGO_HOST:127.0.0.1}
      port: ${SOP_APP_SERVICE_MONGO_PORT:27017}
      username: ${SOP_APP_SERVICE_MONGO_USERNAME:bus-event}
      password: ${SOP_APP_SERVICE_MONGO_PWD:sound99}
      database: ${SOP_APP_SERVICE_MONGO_DATABASE:bus-event}

---
spring:
  profiles: prod
  data:
    mongodb:
      host: ${SOP_APP_SERVICE_MONGO_HOST:172.16.20.14}
      port: ${SOP_APP_SERVICE_MONGO_PORT:27107}
      username: ${SOP_APP_SERVICE_MONGO_USERNAME:bus-event-prod}
      password: ${SOP_APP_SERVICE_MONGO_PWD:bus-event-prod}
      database: ${SOP_APP_SERVICE_MONGO_DATABASE:bus-event-prod}